apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-back-{{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-back-{{.Release.Name}}
    spec:
      containers:
      - name: vote-back-{{.Release.Name}}
        image: "{{ .Values.backend.registry }}@{{ .Values.backend.digest }}"
        ports:
        - containerPort: 6379
          name: "{{ .Values.backend.image }}"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-front-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-front-{{.Release.Name}}
    spec:
      containers:
      - name: "{{ .Values.frontend.image }}"
        image: "{{ .Values.frontend.registry }}@{{ .Values.frontend.digest }}" 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: vote-back-{{.Release.Name}}
        - name: TITLE
          value: {{ .Values.title }}
        - name: VOTE1VALUE
          value: {{ .Values.value1 }}
        - name: VOTE2VALUE
          value: {{ .Values.value2 }}

# Add if operator to env vars
