# Azure Vote UI controll
title: "Azure Vote App"
value1: Cats
value2: Dogs

# how many frontends do we want?
replicaCount: 1

# Service controlls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer
frontend:
  digest: ""
  image: azure-vote-front
  registry: docker.io/neilpeterson
  tag: v3
backend:
  digest: ""
  image: redis
  tag: latest
  registry: docker.io/library